In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Hz_data_32points.csv")
df = pd.DataFrame(data)
df

         z     Hz  sigma_Hz          Reference Correlated
0   0.0700   69.0      19.6       Jimenez_2003         No
1   0.0900   69.0      12.0         Simon_2005         No
2   0.1200   68.6      26.2       Jimenez_2003         No
3   0.1700   83.0       8.0         Simon_2005         No
4   0.1791   75.0       4.0       Moresco_2012        Yes
5   0.1993   75.0       5.0       Moresco_2012        Yes
6   0.2000   72.9      29.6       Jimenez_2003         No
7   0.2700   77.0      14.0         Simon_2005         No
8   0.2800   88.8      36.6       Jimenez_2003         No
9   0.3520   83.0      14.0       Moresco_2012        Yes
10  0.3802   83.0      13.5       Moresco_2016        Yes
11  0.4000   95.0      17.0         Simon_2005         No
12  0.4004   77.0      10.2       Moresco_2016        Yes
13  0.4247   87.1      11.2       Moresco_2016        Yes
14  0.4497   92.8      12.9       Moresco_2016        Yes
15  0.4700   89.0      34.0  Ratsimbazafy_2017         No
16  0.4783   80.9       9.0       Moresco_2016        Yes
17  0.4800   97.0      62.0  Ratsimbazafy_2017         No
18  0.5930  104.0      13.0       Moresco_2012        Yes
19  0.6800   92.0       8.0       Moresco_2012        Yes
20  0.7500   98.8      33.6        Borghi_2022         No
21  0.7810  105.0      12.0       Moresco_2012        Yes
22  0.8750  125.0      17.0       Moresco_2012        Yes
23  0.8800   90.0      40.0  Ratsimbazafy_2017         No
24  0.9000  117.0      23.0         Stern_2010         No
25  1.0370  154.0      20.0       Moresco_2012        Yes
26  1.3000  168.0      17.0         Stern_2010         No
27  1.3630  160.0      33.6       Moresco_2015        Yes
28  1.4300  177.0      18.0         Stern_2010         No
29  1.5300  140.0      14.0         Stern_2010         No
30  1.7500  202.0      40.0         Stern_2010         No
31  1.9650  186.5      50.4       Moresco_2015        Yes

In [3]:
df.describe(include='all')

                z          Hz   sigma_Hz     Reference Correlated
count   32.000000   32.000000  32.000000            32         32
unique        NaN         NaN        NaN             8          2
top           NaN         NaN        NaN  Moresco_2012         No
freq          NaN         NaN        NaN             8         17
mean     0.663991  105.700000  21.200000           NaN        NaN
std      0.512167   37.809744  13.790436           NaN        NaN
min      0.070000   68.600000   4.000000           NaN        NaN
25%      0.277500   79.925000  12.000000           NaN        NaN
50%      0.474150   91.000000  17.000000           NaN        NaN
75%      0.885000  119.000000  30.600000           NaN        NaN
max      1.965000  202.000000  62.000000           NaN        NaN